"""new model

Revision ID: 31c3adf82c64
Revises: 
Create Date: 2021-12-03 22:50:03.211384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c3adf82c64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts_table', sa.Column('client_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts_table', 'client_number')
    # ### end Alembic commands ###
