"""new model 2

Revision ID: 81cb55dca959
Revises: 31c3adf82c64
Create Date: 2021-12-03 22:53:17.842970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cb55dca959'
down_revision = '31c3adf82c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
