"""new model 4

Revision ID: c0c1e32bc688
Revises: 040b28ea6f1b
Create Date: 2021-12-03 22:56:09.416480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c1e32bc688'
down_revision = '040b28ea6f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts_table', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Posts_table', 'users_table', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Posts_table', type_='foreignkey')
    op.drop_column('Posts_table', 'owner_id')
    # ### end Alembic commands ###
